skip_docs

lane :release do
  code_review
  sh('bundle exec rake build')
  gem_path = "pkg/fastlane-plugin-xcmonkey-#{version}.gem"
  sh("gem push ../#{gem_path}")
  set_github_release(
    repository_name: 'alteral/fastlane-plugin-xcmonkey',
    api_token: ENV.fetch("GITHUB_TOKEN", nil),
    name: version,
    tag_name: version,
    description: "See [CHANGELOG.md](https://github.com/alteral/xcmonkey/blob/main/CHANGELOG.md##{version.delete('.')})",
    commitish: git_branch,
    upload_assets: [gem_path]
  )
end

lane :code_review do
  sh('bundle exec rake')
  test
end

lane :test do
  sim = FastlaneCore::Simulator.all.detect { |d| d.name == 'iPhone 14' }
  xcmonkey(bundle_id: 'com.apple.Maps', udid: sim.udid, event_count: 10)
end

def version
  version_path = '../lib/fastlane/plugin/xcmonkey/version.rb'
  File.read(version_path).scan(/\d+/).join('.')
end
